# -*- coding: utf-8 -*-
"""for and while loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RiIMso97G9-0lhokckTtI1w-ku8MTmW0
"""

# 1. Write a program to print all natural numbers from 1 to n. – using while
# loop
num=1
n=int(input())
while num<n:
  print(num)
  num+=1

# 2. Write a program to print all natural numbers in reverse (from n to 1). –
# using while loop
n=int(input())
num=1
while n>num:
  print(n)
  n-=1

# 3. Write a program to print all alphabets from a to z. – using while loop
# Initialize the starting character
char='a'
while char <='z':
  print(char,end=" ")
  char=chr(ord(char)+1)

# 4. Write a program to print all even numbers between 1 to 100. – using
# while loop
n=1
while n<100:
  if n%2==0:
    print(n)
  n+=1

# 5. Write a program to find the sum of all odd numbers between 1 to n.
num=1
n=int(input())
sum=0
while num<n:
  sum+=num
  num+=1
print(sum)

# 6. Write a program to count the number of digits in a number.
number=12342
count=0
while number>0:
  count+=1
  number//=10
print(count)

# 7. Write a program to calculate the sum of digits of a number.
number=123
sum=0
while number>0:
  rem=number%10
  sum+=rem
  number//=10
print(sum)

# 8. Write a program to find the first and last digit of a number.
number=1234
last_digit=number%10
while number>=10:
 number//=10
print(last_digit)
print(number)

# 9. Write a program to find the sum of first and last digit of a number.
number=1014
sum=0
last_digit=number%10
while number>=10:
 number//=10
 sum=number+last_digit
print(sum)

# 10.Write a program to enter a number and print its reverse.
a=int(input())
rev=0
while a>0:
  rev=rev*10+a%10
  a//=10
print(rev)

# 11.Write a program to find the power of a number using for loop.
a=2
b=3
for i in range(a,b):
  print(a**b)

# 12.Write a program to find all factors of a number.
a=25
i=1
while i<=a:
   if a%i==0:
     print(i)
   i+=1

# 13.Write a program to calculate the factorial of a number.
a=5
i=1
f=1
while a>i:
  f=f*i
  i+=1
print(f)

# 14.Write a program to find LCM of two numbers.
num1=12
num2=15
lcm=max(num1,num2)
while True:
  if lcm % num1==0 and lcm % num2==0:
    break
  lcm+=1
print(lcm)

# 15.Write a program to check whether a number is Prime number or not.
number=4
is_prime=True
if number<=1:
  is_prime=False
else:
  for i in range(2,number+1):
    if number%i==0:
      break
    is_prime=False
if is_prime==True:
  print("prime number")
else:
  print('not prime')

# 16.Write a program to print all Prime numbers between 1 to n.
n=int(input())
for i in range(2,n+1):
  is_prime=True
  for j in range(2,i):
    if i%j==0:
      is_prime=False
      break
  if is_prime:
   print(i)

# 17.Write a program to find all prime factors of a number.
n=12
for i in range(2,n+1):
 while n%i==0:
  print(i)
  n//=i

# 18.Write a program to check whether a number is an Armstrong number or
# not.
n=153
sum=0
temp=n
while n>0:
  rem=n%10
  n//=10
  sum=sum+(rem*rem*rem)
if sum==temp:
    print("armstrong number")
else:
    print("not an armstrong number")

#write a program to check whether a no. is strong number or not.
#strong number is a special number whose sum of factorial digits is equal to the original number.
n=145
sum=0
temp=n
while n>0:
  rem=n%10
  f=1
  for i in range(1,rem+1):
    f*=i
  sum+=f
  n//=10
if sum==temp:
  print(f'{sum} is the strong number')
else:
  print(f'{sum} is not the strong number')

# 20.Write a program to check whether a number is perfect number or not

# a. Perfect number is a positive integer which is equal to the sum of
# its proper positive divisors.
n=6
sum=0
for i in range(1,n):
  if n%i==0:
    sum+=i
if sum==n:
  print(f'{n} is a perfect number')
else:
    print(f'{n} is not a perfect number')

# 21.Write a program to print fibonacci series upto n terms
n=8
a,b=0,1
for i in range(1,n+1):
 print(a)
 a,b=b,a+b

# 22.Write a program to find ones complement of a binary number
# a. One's complement of a binary number is defined as value
# obtained by inverting all binary bits. It is the result of swapping all
# 1s to 0s and all 0s to 1s.
binary=input()
complement=" "
for i in binary:
  if i=='0':
    complement+='1'
  elif i=='1':
    complement+='0'
  else:
    print("enter valid number")
else:
 print(f'{complement}')